---

- hosts: all:localhost
  tags:
  - always
  - non-developers
  - developers
  - support
  tasks:
  - { include_tasks: tasks/homebrew-prerequisites.yml }
  vars:
  - homebrew_install_path: /usr/local/Homebrew

- hosts: all:localhost
  tags:
  - always
  - non-developers
  - developers
  - support
  roles:
  - { role: filevault }
  filevault:
  - enable: True

- hosts: all:localhost
  tags:
  - always
  - non-developers
  - developers
  - support
  roles:
  - { role: homebrew }
  - { role: casks }
  vars:
  - cask_apps:
    - adobe-creative-cloud
    - caffeine
    - daisydisk
    - dropbox
    - firefox
    - google-chrome
    - google-drive-file-stream
    #- google-backup-and-sync
    - google-hangouts
    - hosts
    - lastpass
    - microsoft-office
    - skype
    - slack
    - spotify
    - teamviewer


- hosts: all:localhost
  connection: local
  tags:
  - developers
  - support
  roles:
  - { role: casks }
  vars:
  - cask_apps:
    - atom
    - filezilla
    - inviqa/tools/hem
    - iterm2
    - vagrant
    - virtualbox

  - cask_fonts:
    - font-inconsolata-dz
    - font-inconsolata-dz-for-powerline
    - font-source-code-pro
    - font-source-code-pro-for-powerline


...
